name: zunun
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  responsive_sizer: ^3.1.1
  flutter_svg: ^2.0.6
  syncfusion_flutter_charts: ^21.2.9
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.9
  video_player: ^2.6.1
  chewie: ^1.5.0
  dotted_border: ^2.0.0+3
  shimmer: ^3.0.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  get_storage: ^2.1.1
  audioplayers: ^5.2.0
  file_picker: ^6.0.0
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - google_fonts/
    - assets/language/
